config/routes.rb
Rails.application.routes.draw do
  resources :performance_tests
  resources :test_types

  resources :students do
    resources :performance_tests, only: [:index, :new, :show]
  end 

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root 'students#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
    has_many :performance_tests, :dependent => :destroy
    has_many :users, through: :performance_tests
    has_many :test_types, through: :performance_tests

    accepts_nested_attributes_for :performance_tests
    
    validates :name, :grad_year, presence: true
    validates :name, uniqueness: { scope: [:grad_year], message: "and graduation year match an existing student"}

    def self.by_grad_year(year)
        where(grad_year: year)
    end 

    def self.alphabetical
        order("name ASC")
    end 

    def self.filter_students(options)
        students = self.by_grad_year(options[:filter_by_year])
    end 

    def self.search_by_name(options)
        self.where("name LIKE ?", "%" + options + "%")
    end 
   
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_student, only: [:show, :edit, :update, :destroy]
    
    rescue_from ActiveRecord::RecordNotFound, with: :handle_student_not_found

    def index 
        @students = Student.all 
        @students = @students.filter_students(filter_student_params) if filter_student_params.present?
        @students = @students.search_by_name(params[:search_by_name]) if params[:search_by_name].present?
    end

    def show
    end

    def new
        @student = Student.new
    end

    def create
        @student = Student.new(student_params)

        if @student.save
            redirect_to student_path(@student)
        else
            render :new
        end 
    end

    def edit
    end

    def update
        if @student.update(student_params)
            redirect_to student_path(@student)
        else
            render :edit
        end
    end

    def destroy
        @student.destroy
        redirect_to students_path
    end

    def handle_student_not_found
        flash[:error] = "Student not found"
        redirect_to students_path
    end

    private

    def student_params
        params.require(:student).permit(
            :name, 
            :grad_year, 
            performance_tests_attributes:[
                :test_type_id,
                :result,
                :date_taken,
                :notes,
                :user_id
            ]
        )
    end 

    def filter_student_params
        params.permit(:filter_by_year)
    end 

    def set_student
        @student = Student.find(params[:id])
    end

end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/edit.html.erb
<h1>Edit Student</h1>

<%= form_for @student do |f|%>
    <%= show_errors_for(@student)%>
    
    <div>
        <%= f.label :name, "Name:" %>
        <%= f.text_field :name %>
    </div>

    <div>
        <%= f.label :grad_year, "Graduation year:" %>
        <%= f.text_field :grad_year %>
    </div>

    <%= f.submit %>
<% end %>

app/views/students/index.html.erb
<h1>Students</h1>

<div class="button1">
    <%= form_tag(students_path, method: 'get', style: 'display:inline-block;') do %>
        <label for="filter_by_year">Filter by Year</label>
        <select name="filter_by_year">
            <option <%= 'selected' if params[:filter_by_year] == '' %> value="">All</option>
            <option <%= 'selected' if params[:filter_by_year] == '2021' %> value="2021">Seniors</option>
            <option <%= 'selected' if params[:filter_by_year] == '2022' %> value="2022">Juniors</option>
            <option <%= 'selected' if params[:filter_by_year] == '2023' %> value="2023">Sophmores</option>
            <option <%= 'selected' if params[:filter_by_year] == '2024' %> value="2024">Freshman</option>
        </select>
    <%= submit_tag 'Filter'%>
    <% end %>

    <%= form_tag(students_path, method: 'get', style: 'display:inline-block;') do %>
        <label for="search_by_name">Search By Name</label>
        <%= text_field_tag :search_by_name %>
        <%= submit_tag 'Search'%>
    <% end %>
</div>


<div class="button1">
    <p><%= button_to "Add Student", { action: "new"}, method: :get %></p>
</div>

<% @students.alphabetical.each do |student|%>
    <p><%= link_to student.name, student_path(student) %></p>
    <% if student.performance_tests.present? %>
        <p>Latest: <%= student.performance_tests.latest.test_name %> (<%= add_units(student.performance_tests.latest) %>) <%= formatted_time(student.performance_tests.latest) %></p>
    <% end %>
<% end %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= form_for @student do |f|%>
    <%= show_errors_for(@student)%>
    
    <div>
        <%= f.label :name, "Name:" %>
        <%= f.text_field :name %>
    </div>

    <div>
        <%= f.label :grad_year, "Graduation year:" %>
        <%= f.text_field :grad_year %>
    </div>

    <h2>Add Performance Test</h2>

    <%= f.fields_for :performance_tests, @student.performance_tests.build do |performance_test_fields| %>
        <div>
            <%= performance_test_fields.label :test_type_id, "Test Type:" %>
            <%= performance_test_fields.collection_select :test_type_id, TestType.all, :id, :name, prompt: true %>
        </div>
        
        <div>
            <%= performance_test_fields.label :result, "Result:" %>
            <%= performance_test_fields.text_field :result %>
        </div>

        <div>
            <%= performance_test_fields.label :date_taken, "Date:" %>
            <%= performance_test_fields.date_select :date_taken %>
        </div>
        
        <div>
            <%= performance_test_fields.label :notes, "Notes:" %>
            <%= performance_test_fields.text_field :notes %>
        </div>
        <br>
        <%= performance_test_fields.hidden_field :user_id, :value => current_user.id %>

    <% end %>
    
    <%= f.submit %>

<% end %>

app/views/students/show.html.erb
<h1><%= @student.name %></h1>
<p>Class of <%= @student.grad_year %></p>

<div class="button1">
    <%= button_to "Edit Student", { action: "edit"}, method: :get, form: {style: 'display:inline-block;'} %>
    <%= button_to "Delete Student", { action: "destroy"}, method: :delete, data: { confirm: "Are you sure?"}, form: {style: 'display:inline-block;'} %>
</div>

<p><%= link_to "#{@student.name}'s Performance Tests", student_performance_tests_path(@student)%></p>
<p><%= link_to "Add Performance Test", new_student_performance_test_path(@student) %></p>