config/routes.rb
Rails.application.routes.draw do
  resources :performance_tests
  resources :test_types

  resources :students do
    resources :performance_tests, only: [:index, :new, :show]
  end 

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root 'students#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/test_types_controller.rb
class TestTypesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_test_type, only: [:show, :edit, :update]

    rescue_from ActiveRecord::RecordNotFound, with: :handle_test_type_not_found

    def index
        @test_types = TestType.all
    end

    def show
        @performance_tests = @test_type.performance_tests
        @performance_tests = @test_type.performance_tests.filter_tests(filter_test_type_params) if params[:rank] == "top_scores"
    end

    def new
        @test_type = TestType.new
    end

    def create
        @test_type = TestType.new(test_type_params)

        if @test_type.save
            redirect_to test_type_path(@test_type)
        else
            render :new
        end
    end

    def edit
    end

    def update
        if @test_type.update(test_type_params)
            redirect_to test_type_path(@test_type)
        else
            render :edit
        end
    end

    def handle_test_type_not_found
        flash[:error] = "Test type not found"
        redirect_to test_types_path
    end

    private

    def test_type_params
        params.require(:test_type).permit(:name)
    end 

    def set_test_type
        @test_type = TestType.find(params[:id])
    end

    def filter_test_type_params
        params.permit(:rank, :id)
    end 

end

app/helpers/test_types_helper.rb
module TestTypesHelper

end

app/views/test_types/_form.html.erb
<%= form_for test_type do |f|%>
    <%= show_errors_for(test_type)%>
    
    <div>
        <%= f.label :name, "Name:" %>
        <%= f.text_field :name %>
    </div>

    <%= f.submit %>
<% end %>

app/views/test_types/edit.html.erb
<h1>Edit Test Type</h1>
<%= render partial: 'form', locals: { test_type: @test_type } %>

app/views/test_types/index.html.erb
<h1>Test Types</h1>

<div class="button1">
    <p><%= button_to "Add New Test Type", { action: "new"}, method: :get %></p>
</div>

<% @test_types.each do |type| %>
    <p><%= link_to type.name, test_type_path(type) %></p>
<% end %>

app/views/test_types/new.html.erb
<h1>New Test Type</h1>
<%= render partial: 'form', locals: { test_type: @test_type } %>

app/views/test_types/show.html.erb
<h1><%= @test_type.name %></h1>

<div class="button1">
    <%= form_tag(test_type_path, method: 'get') do %>
        <label for="rank">Filter Scores</label>
        <select name="rank">
            <option <%= 'selected' if params[:rank] == '' %> value="">None</option>
            <option <%= 'selected' if params[:rank] == 'top_scores' %> value="top_scores">Top Scores</option>
        </select>
        <%= submit_tag 'Filter'%>
    <% end %>
</div>

<% @performance_tests.each do |performance_test|%>
    <p><%= link_to performance_test.student.name, student_performance_test_path(performance_test.student, performance_test) %>: <%= add_units(performance_test) %></p>
<% end %>

<%= button_to "Edit Test Type", { action: "edit"}, method: :get %>