config/routes.rb
Rails.application.routes.draw do
  resources :performance_tests
  resources :test_types

  resources :students do
    resources :performance_tests, only: [:index, :new, :show]
  end 

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root 'students#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/performance_test.rb
class PerformanceTest < ApplicationRecord
  belongs_to :user
  belongs_to :student
  belongs_to :test_type

  validates :result, :date_taken, presence: true
  validates :result, uniqueness: { scope: [:date_taken, :test_type, :user_id], message: "Performance test has already been recorded for this student."}

  def test_name
    self.test_type.name 
  end 
  
  def self.by_test_type(test_type)
    where(test_type: test_type)
  end 

  def self.latest
    order(date_taken: :desc).first
  end 

  def self.most_recent
    order(date_taken: :desc)
  end 
  
  def self.old
    order(date_taken: :asc)
  end

  def self.top_scores
    order("result DESC").limit(3)
  end 

  def self.top_sprinting_scores
    order("result ASC").limit(3)
  end 

  def self.filter_options(options)
    if options[:filter_by_type]
      results = self.by_test_type(options[:filter_by_type])
    else
      results = self.all
    end 

    if options[:sort] == "most_recent"
        results = results.most_recent
    elsif options[:sort] == "old"
        results = results.old
    end 
    results
  end

  def self.filter_tests(options)
    if options[:id] == "1" || options[:id] == "2"
        tests = self.top_scores
    elsif options[:id] == "3" || options[:id] == "4"
        tests = self.top_sprinting_scores
    end 
  end 

end

app/controllers/performance_tests_controller.rb
class PerformanceTestsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_performance_test, only: [:edit, :update, :destroy]
    before_action :set_student_for_tests, only: [:index, :show, :new]

    rescue_from ActiveRecord::RecordNotFound, with: :handle_performance_test_not_found

    def index
        if @student
            @performance_tests = @student.performance_tests
        else
            @performance_tests = PerformanceTest.all
        end
        @performance_tests = @performance_tests.filter_options(filter_options_params) if filter_options_params.present?
    end

    def show
        @performance_test = @student.performance_tests.find_by(id: params[:id])
    end

    def new
        if @student
            @performance_test = @student.performance_tests.build(student_id: params[:student_id])
        else
            @performance_test = PerformanceTest.new
        end 
        
    end 

    def create
        @performance_test = current_user.performance_tests.build(performance_test_params)
        if @performance_test.save
            redirect_to student_performance_test_path(@performance_test.student, @performance_test)
        else
            render :new
        end 
    end

    def edit
    end

    def update
        if @performance_test.update(performance_test_params)
            redirect_to student_performance_test_path(@performance_test.student, @performance_test)
        else
            render :edit
        end 
    end

    def destroy
        @performance_test.destroy
        redirect_to performance_tests_path
    end

    def handle_performance_test_not_found
        flash[:error] = "You are not authorized to edit performance tests you did not create."
        redirect_to performance_tests_path
    end

    private

    def performance_test_params
        params.require(:performance_test).permit(:notes, :result, :date_taken, :user_id, :student_id, :test_type_id)
    end 

    def set_performance_test
        @performance_test = current_user.performance_tests.find(params[:id])
    end

    def filter_options_params
        params.permit(:filter_by_type, :sort)
    end 

    def set_student_for_tests
        @student = Student.find_by(id: params[:student_id])
    end 

end

app/helpers/performance_tests_helper.rb
module PerformanceTestsHelper

    def formatted_time(test)
        test.date_taken.strftime('%b %Y')
    end 

    def add_units(performance_test)
        if performance_test.test_type_id == 1 || performance_test.test_type_id == 2
            labeled_test = add_inches(performance_test.result)
        else
            labeled_test = add_secs(performance_test.result)
        end
        labeled_test
    end 

    def add_inches(result)
        "#{result} in"
    end 

    def add_secs(result)
        "#{result} sec"
    end 

end

app/views/performance_tests/_all_tests.erb
 <h1>Performance Tests</h1>

<div class="button1">
    <%= form_tag(performance_tests_path, method: 'get') do %>

        <label for="filter_by_type">Filter by Type</label>
        <select name="filter_by_type">
            <option <%= 'selected' if params[:filter_by_type] == '' %> value="">All</option>
            <option <%= 'selected' if params[:filter_by_type] == '1' %> value="1">Vertical Jump</option>
            <option <%= 'selected' if params[:filter_by_type] == '2' %> value="2">Broad Jump</option>
            <option <%= 'selected' if params[:filter_by_type] == '3' %> value="3">40 Meter Sprint</option>
            <option <%= 'selected' if params[:filter_by_type] == '4' %> value="4">Shuttle Run</option>
        </select>

        <label for="sort">Filter by Date</label>
        <select name="sort">
            <option <%= 'selected' if params[:sort] == '' %> value="">None</option>
            <option <%= 'selected' if params[:sort] == 'most_recent' %> value="most_recent">Most Recent</option>
            <option <%= 'selected' if params[:sort] == 'old' %> value="old">Old</option>
        </select>
        <%= submit_tag 'Filter'%>
    <% end %>
</div>

<% @performance_tests.each do |performance_test| %>
    <p><%= link_to performance_test.student.name, student_path(performance_test.student) %>: <%= performance_test.test_name %> (<%= link_to add_units(performance_test), student_performance_test_path(performance_test.student, performance_test) %>) <%= formatted_time(performance_test) %></p>
<% end %>

app/views/performance_tests/_form.html.erb
<%= form_for performance_test do |f|%>
    <%= show_errors_for(performance_test)%>
    
    <div>
        <%= f.label :student_id, "Student:" %>
        <%= f.collection_select :student_id, Student.all, :id, :name, prompt: true %>
    </div>

    <div>
        <%= f.label :test_type_id, "Test Type:" %>
        <%= f.collection_select :test_type_id, TestType.all, :id, :name, prompt: true %>
    </div>

    <div>
        <%= f.label :notes, "Notes:" %>
        <%= f.text_field :notes %>
    </div>

    <div>
        <%= f.label :result, "Result:" %>
        <%= f.text_field :result %>
    </div>

    <div>
        <%= f.label :date_taken, "Date:" %>
        <%= f.date_select :date_taken %>
    </div>

    <%= f.submit %>
<% end %>

app/views/performance_tests/_student_tests.erb
<h1>Performance Tests for: <%= link_to @student.name, student_path(@student) %></h1>

<% @performance_tests.each do |performance_test| %>
    <p><%= performance_test.test_name %>: <%= link_to add_units(performance_test), student_performance_test_path(performance_test.student, performance_test) %> (<%= formatted_time(performance_test) %>)</p>
<% end %>

app/views/performance_tests/edit.html.erb
<h1>Edit Performance Test</h1>
<%= render partial: 'form', locals: { performance_test: @performance_test } %>

app/views/performance_tests/index.html.erb
<% if @student %>
    <%= render partial: 'student_tests', locals: { performance_test: @performance_test }%>
<% else %>
    <%= render partial: 'all_tests', locals: { performance_test: @performance_test }%>
<% end %>

<div class="button1">
    <%= button_to "Add Performance Test", { action: "new"}, method: :get %>
</div>

app/views/performance_tests/new.html.erb
<h1>New Performance Test</h1>
<%= render partial: 'form', locals: { performance_test: @performance_test } %>

app/views/performance_tests/show.html.erb
<h1><%= @student.name %>: <%= @performance_test.test_name %></h1>

<p>Result: <%= add_units(@performance_test) %></p>
<p>Date: <%= formatted_time(@performance_test) %></p>
<p>Coach: <%= @performance_test.user.full_name %></p>

<% if @performance_test.notes.present? %>
    <p>Notes: <%= @performance_test.notes %></p>
<% end %>

<div class="button1">
    <%= button_to "Edit Test", { action: "edit"}, method: :get, form: {style: 'display:inline-block;'} %>
    <%= button_to "Delete Test", { action: "destroy"}, method: :delete, data: { confirm: "Are you sure?"}, form: {style: 'display:inline-block;'} %>
</div>

<p><%= link_to "#{@student.name}'s Performance Tests", student_performance_tests_path(@student)%></p>

<div class="button1">
    <%= button_to "Add Performance Test", { action: "new"}, method: :get %>
</div>